### PR TITLE
Minimal supported node version set to 12 to support globalThis variab…

### PR DESCRIPTION
**Pull request by df-gss**
### What was happening

Unable to build with node version 10, because of the error "ReferenceError: globalThis is not defined", This is added in node 12 see this post [ReferenceError: globalThis is not defined](https://stackoverflow.com/questions/66586352/referenceerror-globalthis-is-not-defined)

By requiring a minimal node version it will be easier for new developers to startup the project, If there is a minimal node version please let me know so I can update my pull request.

### What was done

- Added minimal node version 12 in packages.json
- Added node to recommended tools list

### Test Steps

1. 

### Screenshots

(prefer animated gif)

### Checklist

-   [] tested locally
-   [] documented the code
-   [] clean all warnings and errors of eslint
-   [] requires changes in OutSystems (if so, provide a module with changes)
-   [] requires new sample page in OutSystems (if so, provide a module with changes)

### CODE REVIEW

**Comment by gnbm** [comment]
Hello [@df-gss ](https://github.com/df-gss):wave:
Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the :memo: [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

After this step, we'll review your Pull Request and provide any feedback if needed. 
Finally, just to make you aware, our branch master is "dev" so we'll change the Pull Request to be for that branch.
Thank you and feel free to keep contributing! 🚀

**Comment by df-gss** [comment]
Hi @gnbm 
I read, understood and accept the OutSystems CLA


In the readme it states to start from the master branch, Maybe it's not up-to-date, It wasn't clear to merge to dev.

**Comment by gnbm** [comment]
> 

The master branch is 'dev' not 'main'. But we'll make it more clear in the ReadMe.
Thank you for the feedback!

**Comment by df-gss** [comment]
@gnbm 

> > 
> 
> The master branch is 'dev' not 'main'. But we'll make it more clear in the ReadMe. Thank you for the feedback!

I can see some extra things are added now, If it's better I can start my change from dev and create a pull request the correct way

**Comment by joselrio** [comment]
Hi @df-gss,

Sorry for this, but we must cancel this PR and ask you to do it through the dev branch.
Since you created your NodeVersion branch based on main, that contains docs folder (that is automatically generated at the moment we do a release), we're getting all those files suggested to dev (which we do not want).

That said, we will cancel this PR and please, do it again through the dev branch.

As @gnbm mentioned already, thank you for the feedback and Pull Request :) 

Cheers,
JR

**Pull request closed without merging**
