### PR TITLE
Fix for Idea "Header Alignment in Service Studio for Layout Base of O…

### PR DESCRIPTION
**Pull request by df-gss**
OutSystems UI

This PR is a fix for Idea [Header Alignment in Service Studio for Layout Base of Outsystems UI](https://www.outsystems.com/ideas/13565/header-alignment-in-service-studio-for-layout-base-of-outsystems-ui/)

### What was happening

-  All explained in the Idea

### What was done

- Added CSS provided by Dorine in the idea

### CODE REVIEW

**Comment by BenOsodrac** [comment]
Hello [df-gss](https://github.com/df-gss) 👋

Thanks for your Pull Request. We'll review your Pull Request and provide any feedback if needed.
Thank you and feel free to keep contributing! 🚀

**Comment by gnbm** [comment]
Hello [df-gss](https://github.com/df-gss) :wave:
Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. 
Before we look into your contribution, we need you to accept the :memo: [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

After this step, we'll review your Pull Request and provide any feedback if needed. 
Thank you and feel free to keep contributing! 🚀

**Comment by df-gss** [comment]
I read, understood and accept the OutSystems CLA

**Comment by BenOsodrac** [comment]
Hi @df-gss,

Your improvements were added on the scope of another PR, so that we could add our internal validations: https://github.com/OutSystems/outsystems-ui/pull/841 

As such, I will close this one. thank you again for your contribution!

**Pull request closed without merging**
