### PR TITLE
Updated _display-align.scss for completeness

### PR DESCRIPTION
**Pull request by thekingofspain**
Added absolute flex positioning for all flex directions; primary use case is for supporting flex-direction-column. Added all align-* attributes and their options.

This PR is for...

[Sample page](url)

### What was happening

-

### What was done

-

### Test Steps

1.

### Screenshots

(prefer animated gif)

### Checklist

-   [ ] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

### CODE REVIEW

**Comment by gnbm** [comment]
Hello [thekingofspain](https://github.com/thekingofspain) :wave:
Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the :memo: [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

After this step, we'll review your Pull Request and provide any feedback if needed. 
Thank you and feel free to keep contributing! 🚀

**Review by BenOsodrac — CHANGES_REQUESTED** [review]

**Review by thekingofspain — COMMENTED** [review]
Aggreed, not sure how column got mispelled between my copy and pastes into github.

**Review by thekingofspain — COMMENTED** [review]
asdfsafd

**Comment by gnbm** [comment]
Hello [thekingofspain](https://github.com/thekingofspain) :wave:
Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the :memo: [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

After this step, we'll review your Pull Request and provide any feedback if needed. 
Thank you and feel free to keep contributing! 🚀

**Comment by joselrio** [comment]
Hi @thekingofspain, 

Since till now you didn't accepted OutSystems CLA we can't move forward. Will close the PR.
However your suggestion will be looked by us in order to add some implementation consistency and also make sure we want them as a useful classes.

Thank you for your suggestion.

**Pull request closed without merging**
