### PR TITLE
Update _typography.scss

### PR DESCRIPTION
**Pull request by thekingofspain**
Added italic & oblique font classes

This PR is for...

[Sample page](url)

### What was happening

-

### What was done

-

### Test Steps

1.

### Screenshots

(prefer animated gif)

### Checklist

-   [ ] tested locally
-   [ ] documented the code
-   [ ] clean all warnings and errors of eslint
-   [ ] requires changes in OutSystems (if so, provide a module with changes)
-   [ ] requires new sample page in OutSystems (if so, provide a module with changes)

### CODE REVIEW

**Comment by gnbm** [comment]
Hello [thekingofspain](https://github.com/thekingofspain) :wave:
Thanks for your Pull Request. It looks like this may be your first contribution to an OutSystems Open Source project. Before we look into your contribution, we need you to accept the :memo: [OutSystems Contributors License Agreement](https://outsystems-public-dl.s3-eu-west-1.amazonaws.com/opensource/cla/OutSystems-Contributor-License-Agreement-2020-03-23.pdf).
After you read and accept the terms of the agreement, reply to this message saying `I read, understood and accept the OutSystems CLA`.

After this step, we'll review your Pull Request and provide any feedback if needed. 
Thank you and feel free to keep contributing! 🚀

**Review by BenOsodrac — APPROVED** [review]

**Review by joselrio — APPROVED** [review]

**Comment by thekingofspain** [comment]
I read, understood and accept the OutSystems CLA.
________________________________

**Comment by gnbm** [comment]
Hello [thekingofspain](https://github.com/thekingofspain)
Could you share your OS community email so that we can give you our contribution badge?

**Comment by thekingofspain** [comment]
I have a few, the main one is ***@***.***
________________________________

**Pull request merged**
